# Cinder driver container for Dell EMC VxFlexOS
# Using openstack-cinder-volume base image
# Version 1.0

FROM registry.access.redhat.com/rhosp13/openstack-cinder-volume

MAINTAINER Dell EMC
LABEL description="Red Hat OpenStack Platform 13.0 cinder-volume Dell EMC VxFlexOS" \
      summary="Red Hat OpenStack Platform 13.0 cinder-volume Dell EMC VxFlexOS" \
      name="rhosp13/openstack-cinder-volume-dellemc-vxflexos" \
      vendor="Dell EMC" \
      version="1.0.0"

ARG sdc_binary_path=/opt/emc/scaleio/sdc/bin
ARG sdc_binary_filename=drv_cfg

USER root

RUN mkdir -p $sdc_binary_path
ADD drv_cfg.py $sdc_binary_path/$sdc_binary_filename
RUN chmod -R 0700 $sdc_binary_path

RUN mkdir /licenses
ADD LICENSE /licenses/licensing.txt

USER cinder