# Cinder driver container for Dell EMC VxFlexOS
# Using openstack-cinder-volume base image
# Version 1.0.1

FROM registry.access.redhat.com/rhosp13/openstack-cinder-volume

MAINTAINER Dell EMC
LABEL description="Red Hat OpenStack Platform 13.0 cinder-volume Dell EMC VxFlexOS" \
      summary="Red Hat OpenStack Platform 13.0 cinder-volume Dell EMC VxFlexOS" \
      name="rhosp13/openstack-cinder-volume-dellemc-vxflexos" \
      vendor="Dell EMC" \
      version="1.0.1"

USER root

COPY opt /opt
RUN chmod -R 0700 /opt/emc/scaleio/sdc/bin

COPY LICENSE /licenses/licensing.txt

USER cinder